export const RegisterTypes = {
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  
  CREATE_USER: 'CREATE_USER',
  SELECT_USER: 'SELECT_USER',
  EDIT_USER: 'EDIT_USER',
  UPDATE_USER: 'UPDATE_USER'
};

export default RegisterTypes;
